from .home import home_controller
from .players import players_controller
from .addplayer import add_player_controller
from .listplayers import list_players_controller
from .player import player_controller
from .tournaments import tournaments_controller
from .addtournament import add_tournament_controller
from .listtournaments import list_tournaments_controller
from .tournament import tournament_controller
from .playround import play_round_controller
from .generalranking import general_ranking_controller
from .rounds import rounds_controller
from .changeplayerranking import change_player_ranking_controller
from .logs import logs_controller
from .playersalphabeticorder import players_alphabetic_order_controller
from .playersrankingorder import players_ranking_order_controller
from .tournamentrounds import tournament_rounds_controller
from .tournamentmatchs import tournament_matchs_controller
from .exit import exit_controller
